Chef-Zilla/ViewModels/FoodPlanViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Chef_Zilla.Models;

namespace Chef_Zilla.ViewModels
{
    public class FoodPlanViewModel
    {
        public List<Box> Boxes { get; set; }
        public List<int> RoutineID { get; set; }
        public List<string> RoutineName { get; set; }
        public List<string> RoutineType { get; set; }
        public List<string> BoxName { get; set; }
    }
}

Chef-Zilla/Controllers/FoodPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Chef_Zilla.Models;
using Chef_Zilla.ViewModels;
using Microsoft.AspNet.Identity;

namespace Chef_Zilla.Controllers
{
    [Authorize]
    public class FoodPlanController : Controller
    {
        private ApplicationDbContext _context;

        public FoodPlanController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: FoodPlan
        public ActionResult Index()
        {
            FoodPlanViewModel foodPlanViewModel = new FoodPlanViewModel();
            var userId = User.Identity.GetUserId();
            var box = _context.Boxes.Where(m => m.UserId == userId).ToList();
            var routineId = _context.Routines.Where(x => x.UserId == userId)
                .Select(x => x.RoutineID).ToList();
            var routineName = _context.Routines.Where(x => x.UserId == userId)
                .Select(x => x.RoutineName).ToList();
            var boxId = _context.Routines.Where(x => x.UserId == userId)
                .Select(x => x.BoxID).ToList();
            List<string> BoxName = new List<string>();
            List<string> RoutineType = new List<string>();
            foreach (var item in boxId)
            {
                var boxName = _context.Boxes.Where(x => x.BoxID == item)
                    .Select(x => x.BoxName).ToList();
                BoxName.Add(boxName[0]);
            }
            foreach (var item in routineId)
            {
                var routineType = _context.RoutineSchedules.Where(x => x.RoutineID == item)
                    .Select(x => x.RoutineType).ToList();
                RoutineType.Add(routineType[0]);
            }
            foodPlanViewModel.Boxes = box;
            foodPlanViewModel.RoutineID = routineId;
            foodPlanViewModel.RoutineName = routineName;
            foodPlanViewModel.BoxName = BoxName;
            foodPlanViewModel.RoutineType = RoutineType;
            return View(foodPlanViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RedirectToCreateRoutine(int boxId)
        {
            return RedirectToAction("Create", new RouteValueDictionary(new { controller = "Routine", id = boxId }));
        }
    }
}

Chef-Zilla/Views/FoodPlan/Index.cshtml
@{
    ViewBag.Title = "My Food Plan";
}
@Html.Partial("~/Views/Shared/_NavBar.cshtml")
<br>
<br>
<br>
@if (TempData["message"] != null)
{
    <div id="infoValidationSummary" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>@TempData["message"]</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-10 offset-md-1 ">
            <img class="img-fluid" src="~/Images/Group 38.png" alt="">
        </div>
    </div>

    <div class="row text-center mt-5">
        <div class="col-6 offset-3">
            <img style="width: 80%" src="~/Images/Group 39.png" alt="">
        </div>
    </div>

    <div class="row text-center">
        <div class="col-12 mt-5">
            <h3 class="font-weight-bold">Build your customized box and save for your routine delivery.</h3>
        </div>
        <a href="@Url.Action("Create", "Box")" class="btn buttonCss mx-auto mt-4 text-white">
            Build My Box
        </a>
    </div>
</div>
<div class="container">
    <div class="row text-center mt-5">
        <div class="col-12">
            <h2 class="font-weight-bold">My Available Box</h2>
        </div>
    </div>
    <div class="row">
        @for (var i = 0; i < @Model.Boxes.Count; i++)
        {
            <div class="col-md-4 text-center mt-5">
                <img style="width: 70%;" src="~/Images/gift.png" alt="">
                <a href="@Url.Action("Details", "Box", new {id = @Model.Boxes[i].BoxID})">
                    <h5 class="font-weight-bold">@Model.Boxes[i].BoxName</h5>
                </a>
                @using (Html.BeginForm("RedirectToCreateRoutine", "FoodPlan", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    if (ViewData.ModelState.Keys.Any(k => ViewData.ModelState[k].Errors.Any()))
                    {
                        <div class="row">
                            <div class="col-12 mb-2">
                                <div class="alert alert-warning alert-dismissible show" role="alert">
                                    @Html.ValidationSummary(true, "")
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    }
                    <input type="text" class="d-none" name="boxId" value="@Model.Boxes[i].BoxID" readonly="readonly" />
                    <button type="submit" class="buttonCss mx-auto mt-4">Add To Food Plan</button>
                }
            </div>
        }
    </div>
</div>
<br>
<br>
<br>
<div class="container mt-5">
    <div class="row text-center mt-5">
        <div class="col-12">
            <h2 class="font-weight-bold">My Food Plan</h2>
        </div>
    </div>
    <div class="row">
        @for (var i = 0; i < @Model.RoutineID.Count; i++)
        {
            <div class="col-md-4 text-center mt-5">
                <img style="width: 70%;" src="~/Images/calenderD.png" alt="">
                <a href="@Url.Action("Details", "Routine", new {id = @Model.RoutineID[i]})">
                    <h5 class="font-weight-bold">@Model.RoutineName[i]</h5>
                </a>
                <p class="color">Type: @Model.RoutineType[i]</p>
                <p class="color mt-n3">Box: @Model.BoxName[i]</p>
            </div>
        }
    </div>
</div>
@Html.Partial("~/Views/Shared/_Footer.cshtml")
@section Scripts {
    <script>
    $(document).ready(function () {
        if ("@TempData["message"]" != null) {
            $('#infoValidationSummary').modal('show');
        }
    });
    </script>
}