Chef-Zilla/Models/Routine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chef_Zilla.Models
{
    public class Routine
    {
        public int RoutineID { get; set; }
        public string RoutineName { get; set; }
        public int BoxID { get; set; }
        public string UserId { get; set; }
        public string DeliveryAddress { get; set; }
        public string RoutineStatus { get; set; }
    }
}

Chef-Zilla/Controllers/RoutineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Chef_Zilla.Models;
using Chef_Zilla.ViewModels;
using Microsoft.AspNet.Identity;

namespace Chef_Zilla.Controllers
{
    [Authorize]
    [OutputCache(NoStore = true, Duration = 0)]
    public class RoutineController : Controller
    {
        private ApplicationDbContext _context;

        public RoutineController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Routine
        public ActionResult Create(int id)
        {
            RoutineCreateViewModel routineCreateViewModel = new RoutineCreateViewModel();
            var userId = User.Identity.GetUserId();
            var firstName = _context.Users.Where(m => m.Id == userId).Select(x => x.FirstName).ToList();
            var lastName = _context.Users.Where(m => m.Id == userId).Select(x => x.LastName).ToList();
            var email = _context.Users.Where(m => m.Id == userId).Select(x => x.Email).ToList();
            var phone = _context.Users.Where(m => m.Id == userId).Select(x => x.PhoneNumber).ToList();
            var box = _context.Boxes.Where(m => m.UserId == userId).ToList();
            var price = _context.BoxProducts.Where(m => m.BoxID == id).Select(x => x.TotalPrice).ToList();
            List<int> TotalPrice = new List<int>();
            foreach (var item in box)
            {
                var Price = _context.BoxProducts.Where(m => m.BoxID == item.BoxID).Select(x => x.TotalPrice).ToList();
                var totalPrice = 0;
                foreach (var item1 in Price)
                {
                    totalPrice = totalPrice + item1;
                }
                TotalPrice.Add(totalPrice);
            }
            var totalPriceOfCurrentItem = 0;
            foreach (var item in price)
            {
                totalPriceOfCurrentItem = totalPriceOfCurrentItem + item;
            }
            Console.WriteLine(TotalPrice);
            routineCreateViewModel.Boxes = box;
            routineCreateViewModel.BoxSelectID = id;
            routineCreateViewModel.CustomerName = firstName[0] + " "+ lastName[0];
            routineCreateViewModel.CustomerEmail = email[0];
            routineCreateViewModel.CustomerPhone = phone[0].Remove(0, 3);
            routineCreateViewModel.TotalPrice = totalPriceOfCurrentItem;
            routineCreateViewModel.TotalPriceList = TotalPrice;
            Session["BoxList"] = box;
            Session["TotalPriceList"] = TotalPrice;
            Session["BoxSelectID"] = id;
            return View(routineCreateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoutineCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Console.WriteLine(model.RoutineName);
            Console.WriteLine(model.BoxID);
            Console.WriteLine(model.RoutineType);
            Console.WriteLine(model.DeliveryDay);
            Console.WriteLine(model.DeliveryDate);
            Console.WriteLine(model.CustomerName);
            Console.WriteLine(model.CustomerEmail);
            Console.WriteLine(model.CustomerPhone);
            Console.WriteLine(model.DeliveryAddress);
            Console.WriteLine(model.TotalPrice);
            var userId = User.Identity.GetUserId();
            Routine routine = new Routine();
            routine.RoutineName = model.RoutineName;
            routine.BoxID = model.BoxID;
            routine.UserId = userId;
            routine.DeliveryAddress = model.DeliveryAddress;
            routine.RoutineStatus = "Active";
            _context.Routines.Add(routine);
            _context.SaveChanges();
            int routineId = routine.RoutineID;
            RoutineSchedule routineSchedule = new RoutineSchedule();
            routineSchedule.RoutineType = model.RoutineType;
            var deliveryDay = "";
            if (model.RoutineType == "Weekly")
            {
                for (int i = 0; i < model.DeliveryDay.Count; i++)
                {
                    if (i == model.DeliveryDay.Count - 1)
                    {
                        deliveryDay += model.DeliveryDay[i];
                    }
                    else
                    {
                        deliveryDay += model.DeliveryDay[i] + ",";
                    }
                }
                routineSchedule.DeliveryDay = deliveryDay;
            }
            if (model.RoutineType == "Monthly")
            {
                string[] date = model.DeliveryDate.Split(',');
                var day = "";
                List<int> DayList = new List<int>();

                for (int i = 0; i < date.Length; i++)
                {
                    string[] item = date[i].Split('/');
                    DayList.Add(Int32.Parse(item[1]));
                }
                DayList.Sort();
                for (int i = 0; i < DayList.Count; i++)
                {
                    if (i == DayList.Count - 1)
                    {
                        day += DayList[i];
                    }
                    else
                    {
                        day += DayList[i] + ",";
                    }
                }
                Console.WriteLine(DayList);
                routineSchedule.DeliveryDate = day;
            }
            routineSchedule.RoutineID = routineId;
            routineSchedule.OrderStatus = "pending";
            _context.RoutineSchedules.Add(routineSchedule);
            _context.SaveChanges();
            TempData["message"] = "Routine succesfully created.";
            Session["BoxList"] = null;
            Session["TotalPriceList"] = null;
            Session["BoxSelectID"] = null;
            return RedirectToAction("Index", new RouteValueDictionary(new { controller = "FoodPlan"}));
        }

        public ActionResult Details(int id)
        {
            RoutineDetailsViewModel routineDetailsViewModel = new RoutineDetailsViewModel();
            var routine = _context.Routines.Where(x => x.RoutineID == id).ToList();
            var routineSchedule = _context.RoutineSchedules.Where(x => x.RoutineID == id).ToList();
            int boxId = routine[0].BoxID;
            var boxName = _context.Boxes.Where(m => m.BoxID == boxId).Select(x => x.BoxName).ToList();
            routineDetailsViewModel.RoutineID = id;
            routineDetailsViewModel.RoutineName = routine[0].RoutineName;
            routineDetailsViewModel.BoxName = boxName[0];
            routineDetailsViewModel.RoutineType = routineSchedule[0].RoutineType;
            routineDetailsViewModel.RoutineStatus = routine[0].RoutineStatus;
            routineDetailsViewModel.DeliveredDate = routineSchedule[0].DeliveredDate;
            if (routine[0].RoutineStatus == "Active")
            {
                DateTime today = DateTime.Today;
                Console.WriteLine(today.Day);
                if (routineSchedule[0].RoutineType == "Daily")
                {
                    var newDate = today.AddDays(1);
                    routineDetailsViewModel.UpcomingDeliveryDate = newDate.ToString("dddd: dd MMMM yyyy");
                }
                if (routineSchedule[0].RoutineType == "Weekly")
                {
                    routineDetailsViewModel.DeliveryDay = routineSchedule[0].DeliveryDay;
                    var dayMatch = routineSchedule[0].DeliveryDay.Contains(today.DayOfWeek.ToString());
                    Console.WriteLine(dayMatch);
                    if (dayMatch && routineSchedule[0].OrderStatus == "pending")
                    {
                        routineDetailsViewModel.UpcomingDeliveryDate = today.ToString("dddd: dd MMMM yyyy");
                    }
                    else
                    {
                        string[] day = routineSchedule[0].DeliveryDay.Split(',');
                        for (int i = 1; i < 7; i++)
                        {
                            var newDate = today.AddDays(i);
                            if (routineSchedule[0].DeliveryDay.Contains(newDate.DayOfWeek.ToString()))
                            {
                                routineDetailsViewModel.UpcomingDeliveryDate = newDate.ToString("dddd: dd MMMM yyyy");
                                break;
                            }
                        }
                    }

                }
                if (routineSchedule[0].RoutineType == "Monthly")
                {
                    routineDetailsViewModel.DeliveryDate = routineSchedule[0].DeliveryDate;
                    var dayMatch = routineSchedule[0].DeliveryDate.Contains(today.Day.ToString());
                    Console.WriteLine(dayMatch);
                    if (dayMatch && routineSchedule[0].OrderStatus == "pending")
                    {
                        routineDetailsViewModel.UpcomingDeliveryDate = today.ToString("dddd: dd MMMM yyyy");
                    }
                    else
                    {
                        string[] date = routineSchedule[0].DeliveryDate.Split(',');
                        for (var i = 0; i < date.Length; i++)
                        {
                            var nextDate = Int32.Parse(date[i]);
                            if (nextDate > today.Day)
                            {
                                var newDate = today.AddDays(nextDate - today.Day);
                                routineDetailsViewModel.UpcomingDeliveryDate = newDate.ToString("dddd: dd MMMM yyyy");
                                break;
                            }

                            if (i == date.Length - 1 && !(nextDate > today.Day))
                            {
                                var newDate = today.AddDays(Int32.Parse(date[0]) - today.Day);

Chef-Zilla/Views/Routine/Details.cshtml
@{
    ViewBag.Title = "Routine Details";
}
@Html.Partial("~/Views/Shared/_NavBar.cshtml")
@{
    string[] deliveredDate;
    List<DateTime> DeliveredDate = new List<DateTime>();
    if (!(string.IsNullOrEmpty(Model.DeliveredDate)))
    {
        deliveredDate = Model.DeliveredDate.Split(',');
        foreach (var item in deliveredDate)
        {
            DeliveredDate.Add(DateTime.Parse(item));
        }
    }
}
@if (TempData["message"] != null)
{
    <div id="infoValidationSummary" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>@TempData["message"]</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}
<br>
<br>
<br>
<div class="container-fluid mt-5">
    <div class="row box text-center">
        <div class="col-12">
            <img style="width: 80%;" src="~/Images/Group 42.png" alt="">
        </div>
    </div>
</div>
<div class="container mt-5">
    <div class="row text-center">
        <div class="col-12">
            <h4 class="font-weight-bold">Your Food Plan</h4>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-11 offset-md-1">
            <p class="color" style="font-size: 22px; font-weight:400;">Routine name: @Model.RoutineName</p>
            <p class="color mt-3" style="font-size: 15px; font-weight:400;">Food box: @Model.BoxName</p>
            <p class="color mt-n2" style="font-size: 15px; font-weight:400;">Routine Type: @Model.RoutineType</p>
            <p class="color mt-n2" style="font-size: 15px; font-weight:400;">Delivery Days:</p>
            @if (Model.RoutineType == "Weekly")
            {
                <div class="container-fluid">
                    <div class="row mt-4">
                        <div class="col-1">
                            @if (Model.DeliveryDay.Contains("Saturday"))
                            {
                                <input type="checkbox" class="d-none" id="Saturday" name="DeliveryDay" value="Saturday" checked="checked" disabled="disabled">
                                <label class="days" for="Saturday">Sa</label>
                            }
                            else
                            {
                                <input type="checkbox" class="d-none" id="Saturday" name="DeliveryDay" value="Saturday" disabled="disabled">
                                <label class="days" for="Saturday">Sa</label>
                            }
                        </div>
                        <div class="col-1 ml-3">
                            @if (Model.DeliveryDay.Contains("Sunday"))
                            {
                                <input type="checkbox" class="d-none" id="Sunday" name="DeliveryDay" value="Sunday" checked="checked" disabled="disabled">
                                <label class="days" for="Sunday">Su</label>
                            }
                            else
                            {
                                <input type="checkbox" class="d-none" id="Sunday" name="DeliveryDay" value="Sunday" disabled="disabled">
                                <label class="days" for="Sunday">Su</label>
                            }
                        </div>
                        <div class="col-1 ml-3">
                            @if (Model.DeliveryDay.Contains("Monday"))
                            {
                                <input type="checkbox" class="d-none" id="Monday" name="DeliveryDay" value="Monday" checked="checked" disabled="disabled">
                                <label class="days" for="Monday">Mo</label>
                            }
                            else
                            {
                                <input type="checkbox" class="d-none" id="Monday" name="DeliveryDay" value="Monday" disabled="disabled">
                                <label class="days" for="Monday">Mo</label>
                            }
                        </div>
                        <div class="col-1 ml-3">
                            @if (Model.DeliveryDay.Contains("Tuesday"))
                            {
                                <input type="checkbox" class="d-none" id="Tuesday" name="DeliveryDay" value="Tuesday" checked="checked" disabled="disabled">
                                <label class="days" for="Tuesday">Tu</label>
                            }
                            else
                            {
                                <input type="checkbox" class="d-none" id="Tuesday" name="DeliveryDay" value="Tuesday" disabled="disabled">
                                <label class="days" for="Tuesday">Tu</label>
                            }
                        </div>
                        <div class="col-1 ml-3">
                            @if (Model.DeliveryDay.Contains("Wednesday"))
                            {
                                <input type="checkbox" class="d-none" id="Wednesday" name="DeliveryDay" value="Wednesday" checked="checked" disabled="disabled">
                                <label class="days" for="Wednesday">We</label>
                            }
                            else
                            {
                                <input type="checkbox" class="d-none" id="Wednesday" name="DeliveryDay" value="Wednesday" disabled="disabled">
                                <label class="days" for="Wednesday">We</label>
                            }
                        </div>
                        <div class="col-1 ml-3">
                            @if (Model.DeliveryDay.Contains("Thursday"))
                            {
                                <input type="checkbox" class="d-none" id="Thursday" name="DeliveryDay" value="Thursday" checked="checked" disabled="disabled">
                                <label class="days" for="Thursday">Th</label>
                            }
                            else
                            {
                                <input type="checkbox" class="d-none" id="Thursday" name="DeliveryDay" value="Thursday" disabled="disabled">
                                <label class="days" for="Thursday">Th</label>
                            }
                        </div>
                        <div class="col-1 ml-3">
                            @if (Model.DeliveryDay.Contains("Friday"))
                            {
                                <input type="checkbox" class="d-none" id="Friday" name="DeliveryDay" value="Friday" checked="checked" disabled="disabled">
                                <label class="days" for="Friday">Fr</label>
                            }
                            else
                            {
                                <input type="checkbox" class="d-none" id="Friday" name="DeliveryDay" value="Friday" disabled="disabled">
                                <label class="days" for="Friday">Fr</label>
                            }
                        </div>
                    </div>
                </div>
            }
            @if (Model.RoutineType == "Monthly")
            {
                <input class="d-none" id="DeliveryDate" type="text" value="@Model.DeliveryDate" />
                <div id="datepicker-container" style="display: none;">
                    <div id="select-delivery-date-input"> </div>
                </div>
            }
        </div>
    </div>
    <br>
    <br>
    <div class="row mt-5">
        <div class="col-md-11 offset-md-1">
            <p class="color" style="font-size: 22px; font-weight:bold;">Invoice Information</p>
            <p class="color mt-3" style="font-size: 15px; font-weight:400;">@Model.CustomerName</p>
            <p class="color mt-n2" style="font-size: 15px; font-weight:400;">Email: @Model.CustomerEmail</p>
            <p class="color mt-n2" style="font-size: 15px; font-weight:400;">Phone: @Model.CustomerPhone</p>
            <p class="color mt-n2" style="font-size: 15px; font-weight:400;">Address: @Model.DeliveryAddress</p>
        </div>
    </div>
</div>
@if (DeliveredDate.Count > 0)
{
    <div class="container mt-5">
        <div class="row mt-3">
            <div class="col-md-11 offset-md-1">
                <p class="color" style="font-size: 22px; font-weight:bold;">Delivery completed</p>
            </div>
            <div class="col-md-11 offset-md-1">
                <div class="container-fluid">
                    <div class="row">
                        @foreach (var item in DeliveredDate)
                        {
                            <div class="col-md-4 mt-5">
                                <img style="width: 90%;" src="~/Images/Group 29.png" alt="">
                                <p class="color mt-3" style="font-weight: 400">@item.ToString("dddd: dd MMMM yyyy")</p>
                                <p class="mt-n3 ml-5" style="font-weight: bold; color: #b3b300;">Delivered</p>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="container mt-5">
        <div class="row mt-3">
            <div class="col-md-11 offset-md-1">
                <p class="color" style="font-size: 22px; font-weight:bold;">Delivery completed</p>
            </div>
            <div class="col-md-11 offset-md-1">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12 text-center mt-5">
                            <p class="mt-n3" style="font-weight: bold; color: #b3b300;">This Routine has not delivered yet.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="container mt-5">
    @if (Model.RoutineStatus == "Active")
    {
        <div class="row mt-3">
            <div class="col-md-11 offset-md-1">
                <p class="color" style="font-size: 22px; font-weight: bold;">Upcoming Delivery</p>
            </div>
            <div class="col-md-11 offset-md-1">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4 mt-5">
                            <img style="width: 90%;" src="~/Images/Group 29.png" alt="">
                            <p class="color mt-3" style="font-weight: 400">@Model.UpcomingDeliveryDate</p>
                            <p class="mt-n3 ml-5" style="font-weight: bold; color: grey;">Processing</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <div class="row mt-5 text-center">
        <div class="col-md-6">
            @if (Model.RoutineStatus == "Active")
            {
                <a href="@Url.Action("PauseRoutine", "Routine", new {@routineId = @Model.RoutineID})" class="btn buttonCss text-white">
                    Pause Plan
                </a>
            }
            @if (Model.RoutineStatus == "Pause")
            {
                <a href="@Url.Action("ActivateRoutine", "Routine", new {@routineId = @Model.RoutineID})" class="btn buttonCss text-white">
                    Active Plan
                </a>
            }
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("DeleteRoutine", "Routine", new {@routineId = @Model.RoutineID})" class="btn buttonCssBlue">
                Delete Plan
            </a>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
@Html.Partial("~/Views/Shared/_Footer.cshtml")
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjquerryUi")
    <script>
    $(document).ready(function () {
            var dates = document.getElementById("DeliveryDate").value;
            function padNumber(number) {
                var ret = new String(number);
                if (ret.length == 1)
                    ret = "0" + ret;
                return ret;
            }
            $("#datepicker-container").show();
            $('#select-delivery-date-input').datepicker({
                dateFormat: 'mm/dd/yy',
                stepMonths: 0,
                onSelect: function(selectedDate){
                    console.log(selectedDate);
                },
                beforeShowDay: function (date) {
                    var day = padNumber(date.getDate());
                    console.log(day);
                    var gotDate = dates.includes(day);
                    console.log(gotDate);
                    console.log(dates.includes(day));
                    if (gotDate) {
                        return [true, "ui-state-highlight"];
                    }
                    return [true, ""];
                }
            });
            $("#select-delivery-date-input").datepicker("disable");
            if ("@TempData["message"]" != null) {
                $('#infoValidationSummary').modal('show');
            }
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}